// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjuxdvnrnogvqonobyns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqdXhkdm5ybm9ndnFvbm9ieW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODA3NjIsImV4cCI6MjA1ODU1Njc2Mn0.aU-YWNN0gNZjKp7RErJg1xduX0C5yR8c_95LSeOYgag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);